### ISSUE TITLE
Integration with SpikeInterface

### ISSUE THREAD

**Issue by alejoe91** [jwouters91/shybrid#1]
Hi @jwouters91 

Really nice tool :) I believe that SHYBRID and MEArec will definitely provide new ground-truth datasets for spike sorting validation.

I wanted to ask you if you have time to implement an SHYBRID extractors for [SpikeInterface](https://github.com/SpikeInterface/spikeextractors). SpikeInterface is a unified framework from spike sorting, in which we interface with recording systems/simulators and wrap several spike sorting algorithms ([spikesorters](https://github.com/SpikeInterface/spikesorters)). You can check out the [MEArec extractors](https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/mearecextractors/mearecextractors.py) here to see what is it about.

We also have tools for preprocessing, postprocessing, validation, and automatic curation ([spiketoolkit](https://github.com/SpikeInterface/spiketoolkit)), as well as integrated comparison tools both for ground-truth recordings and spike sorting outputs ([spikecomparison](https://github.com/SpikeInterface/spikecomparison)), and visualization tools ([spikewidgets](https://github.com/SpikeInterface/spikewidgets)).

SpikeInterface is lso the engine running behind [SpikeForest](https://spikeforest.flatironinstitute.org/), a web interface for benchmarking spike sorting on a large variety of gt datasets. I would be great to add some SHYBRID datasets there @magland.

Let me know what you think and please don't hesitate to contact me or any other of the team with issues or directly via email.

Cheers,
Alessio

**Comment by jwouters91** [comment]
Hi @alejoe91 

Thanks for reaching out and all of the interesting pointers! The integration you propose is a very good idea. I will check the implementation details later this week and will try to get a feeling for how much work this is going to be.

Cheers,
Jasper

**Comment by jwouters91** [comment]
https://github.com/jwouters91/spikeextractors/commit/f96e006f856e2666157d3f6e226c795ea6f57c7a

**Comment by jwouters91** [comment]
Hi @alejoe91 

I worked on a first version of the extractors (https://github.com/jwouters91/spikeextractors/commit/cd64ee77cc10bc1be19d016d0d6dcea6b95e9083). It would be nice if you could take a look at that code and provide me some feedback, before I proceed with a merge request. I'm not entirely sure whether I've used the functionality to load the probe file in a legit way... I've also added an example to the examples folder of this project for using those extractors in a spike sorting validation setting (https://github.com/jwouters91/shybrid/commit/4fdbda242d8ad6121ca136a7369321e4e55ac805). The example runs fine on my local environment.

Cheers,
Jasper

**Comment by alejoe91** [comment]
Hi @jwouters91 

It looks good. I would remove the load probe file as tat should be done externally by the user (in all extractors). 

Regarding the validation, I think the that the nice thing of SpikeInterface is that everything is integrated! Please take a look at the comparison examples here: https://spikeinterface.readthedocs.io/en/latest/modules/index.html#comparison-tutorials

These example wokr with any extractor.

Cheers,
Alessio

**Comment by alejoe91** [comment]
@jwouters91 can you make a PR to spikeextractors so we can properly review and test the extractor?

**Comment by jwouters91** [comment]
@alejoe91 I'll proceed with the PR tomorrow

**Comment by jwouters91** [comment]
https://github.com/SpikeInterface/spikeextractors/pull/297

**Comment by jwouters91** [comment]
SHYBRID documentation to be updated before closing this issue
