### ISSUE TITLE
Error installing Shybrid in Linux --> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. 

### ISSUE THREAD

**Issue by Tampu** [jwouters91/shybrid#11]
Hi Jasper,

Thank you for a great tool to generate ground truth data. I have been using Shybrid on Windows and a server where it works perfectly fine but that seems to be a login server so I need to shift to another computer server.

![image](https://user-images.githubusercontent.com/26931797/116880735-a7434000-ac22-11eb-9904-638996202676.png)

I am unable to run Shybrid in the other servers now as it throws the following error: 

![image](https://user-images.githubusercontent.com/26931797/116879795-67c82400-ac21-11eb-93ab-4b6be68a1cca.png)

I have tried reinstalling multiple times but doesn't help. The ldd output is as follows: 

ldd /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so
/imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: /lib64/libdbus-1.so.3: no version information available (required by /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5)
	linux-vdso.so.1 =>  (0x00007ffe78b05000)
	libQt5XcbQpa.so.5 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5 (0x00007fe40a245000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fe409fcd000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fe409d25000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe409b0d000)
	libQt5Gui.so.5 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5Gui.so.5 (0x00007fe4092bd000)
	libQt5DBus.so.5 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5 (0x00007fe40902d000)
	libQt5Core.so.5 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5Core.so.5 (0x00007fe40887d000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007fe40860d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe4083ed000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007fe4081e5000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fe407fbd000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007fe407dad000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007fe407b95000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fe407855000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe40754d000)
	libxkbcommon-x11.so.0 => not found
	libxkbcommon.so.0 => not found
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe407345000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe40703d000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe406e25000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe406a5d000)
	libxkbcommon-x11.so.0 => not found
	libxkbcommon.so.0 => not found
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007fe406855000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fe40651d000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fe4062ed000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007fe4060a5000)
	libicui18n.so.56 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libicui18n.so.56 (0x00007fe405c05000)
	libicuuc.so.56 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libicuuc.so.56 (0x00007fe40584d000)
	libicudata.so.56 => /imec/windows/measpike/raviku53/anaconda3/envs/shybrid_env/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libicudata.so.56 (0x00007fe403e65000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe40a7f5000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007fe403c5d000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007fe403a55000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007fe403845000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007fe40363d000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007fe40342d000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00007fe403225000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007fe40301d000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007fe402e15000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00007fe402be5000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe4029bd000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007fe4027b5000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007fe4025ad000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007fe40238d000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007fe402185000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007fe401f7d000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007fe401d6d000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fe401b65000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe40195d000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fe4016f5000)

![image](https://user-images.githubusercontent.com/26931797/116880414-44ea3f80-ac22-11eb-96cd-af39a4ad4e3d.png)

The libxkbcommon-x11.so.0 and libxkbcommon.so.0 files which are missing from the computer server can be found in login server 
![image](https://user-images.githubusercontent.com/26931797/116881201-3f412980-ac23-11eb-9b74-33b444cdc87c.png)

This seems to be like a very specific issue but if you could kindly look into this I would be grateful. 

Thank you,
Tampu

**Comment by jwouters91** [comment]
Dear Tampu,

Can you check the following Q&A and try to connect with x forwarding switched on:
https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely

In case you can't get it to run, I suggest you contact an imec sys admin.

Best,
Jasper

**Comment by Tampu** [comment]
Dear Jasper, 

Thank you very much for your quick reply. For now I found another server where I am able to run it. I will try switching on x forwarding in future if I face the same issue. I will close this issue now. 

Kind regards,
Tampu
