### ISSUE TITLE
Validate_from_phy needs spike_clusters.npy that doesn't exist

### ISSUE THREAD

**Issue by maartensc** [jwouters91/shybrid#3]
After running spike sorting (using spikeinterface), the results can be converted to phy. When using the command `spyking-circus path/recording.npy -m converting -c N` in the terminal, this creates the needed files, except for spike_clusters.npy, which leads to an error when running the function validation.validate_from_phy.

This is solved by manually copying the created file spike_templates.npy and naming this copy spike_clusters.npy.

**Comment by jwouters91** [comment]
The spike_clusters.npy only get created after manual curation using phy. Since the functionality you are using is meant to be executed on non-curated results, this is clearly a bug. The work around you propose is good for now, but I will fix the bug in code also.
