### ISSUE TITLE
Relax matplotlib version

### ISSUE THREAD

**Issue by alejoe91** [jwouters91/shybrid#9]
Hi @jwouters91 

The `matplotlib==3.1.2` dependency od shybrid is creating some incopatibilities in spikeextractor tests. Is there a specific reason for that version? 

Could you use maybe `>=`?

Cheers
Alessio

**Comment by jwouters91** [comment]
Hi @alejoe91 

I used to have some compatibility issues using newer versions, and I think it was related to the QT backend for Matplotlib. I can check whether this issue still exists. Are you in a hurry with this issue or can I leave it aside for two weeks?

Best,
Jasper

**Comment by alejoe91** [comment]
Thanks for the quick reply! @jwouters91 

I can temporarily disabled shybrid tests and add them back once this compatibility issue is fixed. :)

**Comment by jwouters91** [comment]
I'll get back to you when I have investigated this @alejoe91. It's on the planning!

**Comment by jwouters91** [comment]
@alejoe91 I have relaxed the matplotlib version in the setup script, which seems to now work fine here. I also uploaded a new package to PyPI, so the tests can be re-enabled. Sorry for the delay in testing and adjusting this little thingy.

**Comment by alejoe91** [comment]
Great! Thanks :) I'll reinsert the tests
